name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        jdk:
          - 21
          - 25
        gradle:
          - current
        include:
          - jdk: 8
            gradle: 8.14.5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: ${{ matrix.gradle }}
      - name: Run build
        run: gradle check
